from app.database import SQLALCHEMY_DATABASE_URL, Base, SessionLocal, create_engine_kwargs, engine, get_db, resolve_database_url
from app.main import app
from app.models import (
    AIGeneration,
    Assumption,
    Artist,
    Decision,
    Evidence,
    Fact,
    Gate,
    Order,
    Project,
    ProjectVersion,
    ReportShare,
    Risk,
    Show,
    Task,
    Tenant,
    TenantMember,
    User,
    UserGroup,
)
from app.routes import (
    agent_chat,
    ai_generate,
    create_assumption,
    create_decision,
    create_fact,
    create_gate,
    create_project,
    create_project_version,
    create_risk,
    create_task,
    finance_breakeven,
    finance_calculate,
    get_artist,
    get_project,
    get_show,
    list_assumptions,
    list_artists,
    list_evidences,
    list_facts,
    list_gates,
    list_project_versions,
    list_projects,
    list_risks,
    list_shows,
    list_tasks,
    list_tenants,
    order_show,
    ping,
    search_cases,
    share_report,
    submit_task,
    switch_tenant,
    upload_evidence,
    verify_fact,
    web_login,
    wechat_login,
)
from app.schemas import AIGenerateIn, ArtistOut, DecisionIn, FinanceCalculateIn, OrderIn, ProjectIn, ShowOut, TaskIn, WebLoginIn
from app.services import (
    calculate_breakeven_result,
    calculate_finance_result,
    get_default_tenant_id,
    get_or_create_default_context,
    init_db,
    project_input_snapshot,
    seed_initial_data,
    serialize_assumption,
    serialize_evidence,
    serialize_fact,
    serialize_gate,
    serialize_project,
    serialize_report_share,
    serialize_risk,
    serialize_task,
    serialize_version,
)


if __name__ == '__main__':
    import uvicorn

    uvicorn.run('main:app', host='0.0.0.0', port=8000, reload=False)
