export default defineAppConfig({
  pages: [
    'pages/s01/index',
    'pages/s02/index',
    'pages/s03/index',
    'pages/s04/index',
    'pages/s05/index',
    'pages/s06/index',
    'pages/s07/index',
    'pages/s08/index',
    'pages/s09/index',
    'pages/s10/index',
    'pages/s11/index',
    'pages/s12/index',
    'pages/s13/index',
    'pages/s14/index',
    'pages/s15/index',
    'pages/s16/index',
    'pages/s17/index',
    'pages/s18/index',
    'pages/s19/index',
    'pages/s20/index',
    'pages/s21/index',
    'pages/s22/index',
    'pages/s23/index',
    'pages/s24/index',
    'pages/s25/index',
    'pages/s26/index',
    'pages/s27/index',
    'pages/s28/index',
    'pages/s29/index',
    'pages/s30/index',
    'pages/s31/index',
    'pages/s32/index',
    'pages/s33/index',
    'pages/s34/index',
    'pages/s35/index',
    'pages/s36/index',
    'pages/s37/index',
    'pages/s38/index',
    'pages/s39/index',
    'pages/s40/index',
    'pages/s41/index',
    'pages/s42/index',
    'pages/s43/index',
    'pages/s44/index',
    'pages/s45/index',
    'pages/s46/index',
    'pages/s47/index',
    'pages/s48/index',
    'pages/s49/index',
    'pages/s50/index',
    'pages/s51/index',
    'pages/s52/index',
    'pages/s53/index',
    'pages/s54/index',
    'pages/s55/index',
    'pages/s56/index',
    'pages/s57/index',
    'pages/s58/index',
    'pages/s59/index',
    'pages/s60/index',
    'pages/s61/index',
    'pages/s62/index',
    'pages/s63/index',
    'pages/s64/index',
    'pages/s65/index',
    'pages/s66/index',
    'pages/s67/index',
    'pages/s68/index',
    'pages/s69/index',
    'pages/s70/index',
    'pages/s71/index',
    'pages/s72/index',
    'pages/s73/index',
    'pages/s74/index',
    'pages/s75/index',
    'pages/s76/index',
    'pages/s77/index',
    'pages/s78/index',
    'pages/s79/index',
    'pages/s80/index',
    'pages/s81/index',
    'pages/s82/index',
    'pages/s83/index',
    'pages/s84/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '锐音场',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#86909c',
    selectedColor: '#2864dc',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/s04/index',
        text: '发现',
        iconPath: 'assets/tabbar/discover.svg',
        selectedIconPath: 'assets/tabbar/discover-selected.svg',
      },
      {
        pagePath: 'pages/s10/index',
        text: '项目',
        iconPath: 'assets/tabbar/project.svg',
        selectedIconPath: 'assets/tabbar/project-selected.svg',
      },
      {
        pagePath: 'pages/s52/index',
        text: 'Agent',
        iconPath: 'assets/tabbar/agent.svg',
        selectedIconPath: 'assets/tabbar/agent-selected.svg',
      },
      {
        pagePath: 'pages/s67/index',
        text: '我的',
        iconPath: 'assets/tabbar/profile.svg',
        selectedIconPath: 'assets/tabbar/profile-selected.svg',
      },
    ],
  },
})
