import axios from 'axios'

const API = axios.create({ baseURL: 'http://localhost:8000' })

export const searchArtist = (q) => API.get(`/artists?q=${encodeURIComponent(q)}`)
export const generateAI = (data) => API.post('/ai/generate', data)
export const listShows = (city) => API.get(`/shows?city=${encodeURIComponent(city || '')}`)
export const getShow = (id) => API.get(`/shows/${id}`)
export const mockOrder = (id, data) => API.post(`/shows/${id}/order`, data)
export const webLogin = (data) => API.post('/auth/web-login', data)
export const listUsers = () => API.get('/users')
export const createUser = (data) => API.post('/users', data)
export const updateUser = (id, data) => API.patch(`/users/${id}`, data)
export const deleteUser = (id) => API.delete(`/users/${id}`)
export const listUserGroups = () => API.get('/user-groups')
export const listTenants = () => API.get('/tenants')
export const switchTenant = (tenantId) => API.post(`/tenants/switch?tenant_id=${encodeURIComponent(tenantId)}`)
export const listProjects = () => API.get('/projects')
export const createProject = (data) => API.post('/projects', data)
export const getProject = (id) => API.get(`/projects/${id}`)
export const listProjectVersions = (id) => API.get(`/projects/${id}/versions`)
export const createProjectVersion = (id, data) => API.post(`/projects/${id}/versions`, data)
export const calculateFinance = (data) => API.post('/finance/calculate', data)
export const calculateBreakeven = (data) => API.post('/finance/breakeven', data)
export const createDecision = (data) => API.post('/decisions', data)
export const listTasks = (projectId) => API.get(`/tasks${projectId ? `?project_id=${encodeURIComponent(projectId)}` : ''}`)
export const createTask = (data) => API.post('/tasks', data)
export const submitTask = (id, data) => API.post(`/tasks/${id}/submit`, data)
export const listFacts = (projectId) => API.get(`/facts${projectId ? `?project_id=${encodeURIComponent(projectId)}` : ''}`)
export const createFact = (data) => API.post('/facts', data)
export const verifyFact = (id, data) => API.post(`/facts/${id}/verify`, data)
export const listAssumptions = (projectId) => API.get(`/assumptions${projectId ? `?project_id=${encodeURIComponent(projectId)}` : ''}`)
export const createAssumption = (data) => API.post('/assumptions', data)
export const listEvidences = (projectId, factId) => {
  const params = new URLSearchParams()
  if (projectId) params.set('project_id', projectId)
  if (factId) params.set('fact_id', factId)
  const query = params.toString()
  return API.get(`/evidences${query ? `?${query}` : ''}`)
}
export const createEvidence = (data) => API.post('/evidences/upload', data)
export const listGates = (projectId) => API.get(`/gates${projectId ? `?project_id=${encodeURIComponent(projectId)}` : ''}`)
export const createGate = (data) => API.post('/gates', data)
export const listRisks = (projectId) => API.get(`/risks${projectId ? `?project_id=${encodeURIComponent(projectId)}` : ''}`)
export const createRisk = (data) => API.post('/risks', data)
export const agentChat = (data) => API.post('/agent/chat', data)
export const searchCases = (q) => API.get(`/cases/search?q=${encodeURIComponent(q || '')}`)
export const shareReport = (projectId, data) => API.post(`/reports/${projectId}/share`, data)

export default API
